### ISSUE TITLE
File upload not working with latest community store

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store_shipping_tablerate#2]
I have a clean install of the most recent Community Store on concrete5 5.7.5.13 and the Tables Rates extension and the file selection tool is not showing after the shipping method is added.

The page is stuck with the message: 'You need to add the method first. After adding, edit the shipping method to add the csv file.'

**Comment by Jozzeh** [comment]
I've tested it on a 5.7.5.13 , but could not replicate the issue. 

Please have a look at the latest commit.
https://github.com/concrete5-community-store/community_store_shipping_tablerate/commit/ba146dd9c63296aa17c316939cea41f708a4135b

I think the table rate is the first shipping method you have added in the store. 
Because it is the first shipping method -> ID of the shipping method = 0 .
In the code I checked if the shipping method ID is empty, however the empty function sees a 0 as empty.
I've changed the check to null instead of empty.

**Comment by katalysis** [comment]
@Jozzeh I'm afraid this is still not working for me, I updated the code with your amendment and I'm still seeing the 'You need to add the method first. After adding, edit the shipping method to add the csv file.' message.  I've tried this on two separate installs.

**Comment by Jozzeh** [comment]
katalysis gave me access to his dev website to solve the issue. I have committed the changes to the repo.
