### ISSUE TITLE
No Shipping Options

### ISSUE THREAD

**Issue by pixoinc** [concrete5-community-store/community_store_shipping_tablerate#3]
Thanks for a useful add-on.  I'm using it for the first time and have a quick question.  I believe I have everything in place and the table based shipping is enabled, but when checking out I'm getting:

"There are no shipping options to process your order"

I had two items in my cart.

I've attached screenshots of my settings and CSV.  Could you take a peak and let me know if I've missed something?  Thanks for your help.

![noshipping](https://user-images.githubusercontent.com/11245856/31720492-f4afde02-b3d3-11e7-9ab0-e38e245aaba3.PNG)

![shippingsettings](https://user-images.githubusercontent.com/11245856/31720504-fac70310-b3d3-11e7-998f-477406fff7d8.PNG)

![shippingcsv](https://user-images.githubusercontent.com/11245856/31720509-ff8ba068-b3d3-11e7-8c07-c1552abec28e.PNG)

**Comment by Jozzeh** [comment]
Can you try and set the maximum purchase amount to  0 ...

The maximum purchase amount is actually the total of the cart. With your current setting if the total of your cart is more than 16 euro or dollars or whatever... then the tablerate will not be available.

**Comment by pixoinc** [comment]
Thanks for the quick reply.  I've set the minimum and maximum to zero and still getting the "There are no shipping options to process your order" message in the checkout.

**Comment by Jozzeh** [comment]
Hi , 

I am currently testing it, however when testing but I encountered an error in your csv.  
When editing the shipping rate, at the bottom it says :  
To create a csv file compatible with this package, you should create a csv file which has the same structure as a Magento Table rate.  
**Important: Use two letter codes to generate a csv file.**

Your country code is 3 letters instead of 2...  If you want to easely generate the csv, use the online generator (link also at the bottom where you edit the shipping method). That generator gives you 2 letter codes.  
( [https://elgentos.nl/tablerates/?twoLetterCodes](https://elgentos.nl/tablerates/?twoLetterCodes) )   
The 2 letter code for the United States of America is US .

I'll continue my testing, and I'll edit this post if anything else comes up.

*** Edit ***  
No issues found in the code / functionality of the package as it is now.    
Maybe I need to change the location of the explanation, so it is more in view...

**Comment by pixoinc** [comment]
Thanks for your help.
